server.port=28852
management.endpoints.web.exposure.include=*
spring.application.name=hyperskill-antifraud
spring.jackson.serialization.INDENT_OUTPUT=true
spring.datasource.url=jdbc:h2:file:${user.dir}/service_db
spring.jpa.hibernate.ddl-auto=update
